if(NOT EXISTS "${ESPHOME_EXECUTABLE}")
  message(FATAL_ERROR "Schema checks require ESPHOME_EXECUTABLE")
endif()
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
file(READ "${PROJECT_DIR}/tests/fixtures/schema-base.yaml" base)
string(REPLACE "@COMPONENTS@" "${PROJECT_DIR}/components" base "${base}")
string(REPLACE "build_path: build" "build_path: ${OUTPUT_DIR}/build" base "${base}")

function(check_case name content expected diagnostic)
  set(path "${OUTPUT_DIR}/${name}.yaml")
  file(WRITE "${path}" "${content}")
  execute_process(COMMAND "${CMAKE_COMMAND}" -E env PYTHONDONTWRITEBYTECODE=1
      "${ESPHOME_EXECUTABLE}" config "${path}"
      RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 60)
  file(WRITE "${OUTPUT_DIR}/${name}.log" "${output}${error}")
  if(expected)
    if(NOT result EQUAL 0)
      message(FATAL_ERROR "${name}: expected valid configuration: ${output}${error}")
    endif()
  else()
    if(result EQUAL 0 OR NOT "${output}${error}" MATCHES "${diagnostic}")
      message(FATAL_ERROR "${name}: wrong rejection (${result}), expected '${diagnostic}': ${output}${error}")
    endif()
  endif()
endfunction()

check_case(default "${base}" TRUE "")
function(check_typed_positions path expected)
  file(READ "${path}" code)
  string(REGEX MATCHALL "new\\([^)]*\\) yiscaxia::YiscaxiaLightState\\(" typed "${code}")
  list(LENGTH typed count)
  if(NOT count EQUAL expected OR code MATCHES "new\\([^)]*\\) light::LightState\\(")
    message(FATAL_ERROR "Expected ${expected} typed position states in ${path}, got ${count}")
  endif()
endfunction()
execute_process(COMMAND "${CMAKE_COMMAND}" -E env PYTHONDONTWRITEBYTECODE=1
    "${ESPHOME_EXECUTABLE}" compile "${OUTPUT_DIR}/default.yaml" --only-generate
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 120)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "default codegen failed: ${output}${error}")
endif()
check_typed_positions("${OUTPUT_DIR}/build/src/main.cpp" 12)
foreach(capacity IN ITEMS 6 12 64)
  string(REPLACE "  id: pixel_controller\n" "  id: pixel_controller\n  position_capacity: ${capacity}\n" content "${base}")
  check_case(capacity-${capacity} "${content}" TRUE "")
  file(READ "${OUTPUT_DIR}/capacity-${capacity}.log" validated)
  string(REGEX MATCHALL "id: pixel_controller_position_[0-9]+\n" ids "${validated}")
  list(LENGTH ids count)
  if(NOT count EQUAL capacity)
    message(FATAL_ERROR "capacity-${capacity}: expected ${capacity} stable lights, got ${count}")
  endif()
endforeach()
foreach(capacity IN ITEMS 5 65)
  string(REPLACE "  id: pixel_controller\n" "  id: pixel_controller\n  position_capacity: ${capacity}\n" content "${base}")
  check_case(capacity-${capacity} "${content}" FALSE "position_capacity")
endforeach()
foreach(pairs IN ITEMS "1A,2B,2D" "1A,-,2D" "" "1A,-,-")
  string(MD5 case_id "${pairs}")
  string(REPLACE "  id: pixel_controller\n" "  id: pixel_controller\n  initial_pairs: '${pairs}'\n" content "${base}")
  check_case(pairs-${case_id} "${content}" TRUE "")
endforeach()
foreach(pairs IN ITEMS "1a" "01A" "49A" "1G" "1A,1A" "1A," "1A, 2B" "1A,1B,1C,1D,1E,1F,2A")
  string(MD5 case_id "${pairs}")
  string(REPLACE "  id: pixel_controller\n" "  id: pixel_controller\n  position_capacity: 6\n  initial_pairs: '${pairs}'\n" content "${base}")
  check_case(bad-pairs-${case_id} "${content}" FALSE "channel|unique|exceeds")
endforeach()
foreach(mode IN ITEMS MODE0 0)
  string(REPLACE "    type: md7105\n" "    type: md7105\n    spi_mode: ${mode}\n    data_rate: 1MHz\n" content "${base}")
  check_case(mode-${mode} "${content}" TRUE "")
endforeach()
foreach(mode IN ITEMS MODE1 MODE2 MODE3)
  string(REPLACE "    type: md7105\n" "    type: md7105\n    spi_mode: ${mode}\n" content "${base}")
  check_case(mode-${mode} "${content}" FALSE "MODE0")
endforeach()
foreach(rate IN ITEMS 500kHz 2MHz)
  string(REPLACE "    type: md7105\n" "    type: md7105\n    data_rate: ${rate}\n" content "${base}")
  check_case(rate-${rate} "${content}" FALSE "1000000")
endforeach()
string(REPLACE "type: md7105" "type: unknown" content "${base}")
check_case(unknown-backend "${content}" FALSE "md7105")
foreach(pin IN ITEMS "  mosi_pin: GPIO23\n" "  miso_pin: GPIO19\n" "    cs_pin: GPIO5\n")
  string(MD5 case_id "${pin}")
  string(REPLACE "${pin}" "" content "${base}")
  check_case(missing-pin-${case_id} "${content}" FALSE "mosi_pin|miso_pin|cs_pin")
endforeach()
file(READ "${PROJECT_DIR}/tests/fixtures/static-effects.yaml" effects)
string(REPLACE "esphome:\n" "" effects "${effects}")
string(REPLACE "  build_path: ${OUTPUT_DIR}/build\n" "  build_path: ${OUTPUT_DIR}/build\n${effects}" content "${base}")
string(APPEND content "  rainbow_degrees_per_step:\n    id: pixel_rainbow_step\n    name: Custom Rainbow degrees per step\n  rainbow_step_spacing:\n    id: pixel_rainbow_spacing\n    name: Custom Rainbow step spacing\n")
check_case(static-effects "${content}" TRUE "")
execute_process(COMMAND "${CMAKE_COMMAND}" -E env PYTHONDONTWRITEBYTECODE=1
    "${ESPHOME_EXECUTABLE}" compile "${OUTPUT_DIR}/static-effects.yaml" --only-generate
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 120)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "static-effects codegen failed: ${output}${error}")
endif()
file(READ "${OUTPUT_DIR}/build/src/main.cpp" generated)
check_typed_positions("${OUTPUT_DIR}/build/src/main.cpp" 12)
foreach(boundary IN ITEMS
    "pixel_pairs->traits.set_max_length(47)"
    "pixel_attempts->traits.set_min_value(1)"
    "pixel_attempts->traits.set_max_value(yiscaxia::configuration_setting_max(yiscaxia::YiscaxiaSetting::TRANSMISSION_ATTEMPTS))"
    "pixel_spacing->traits.set_min_value(1)"
    "pixel_spacing->traits.set_max_value(yiscaxia::configuration_setting_max(yiscaxia::YiscaxiaSetting::CHANNEL_SPACING))"
    "pixel_rainbow_step->traits.set_min_value(1)"
    "pixel_rainbow_step->traits.set_max_value(yiscaxia::configuration_setting_max(yiscaxia::YiscaxiaSetting::RAINBOW_STEP_DEGREES))"
    "pixel_rainbow_spacing->traits.set_min_value(1)"
    "pixel_rainbow_spacing->traits.set_max_value(yiscaxia::configuration_setting_max(yiscaxia::YiscaxiaSetting::RAINBOW_STEP_SPACING))")
  string(FIND "${generated}" "${boundary}" found)
  if(found LESS 0)
    message(FATAL_ERROR "Missing generated entity boundary: ${boundary}")
  endif()
endforeach()
string(REGEX MATCHALL "set_effect\\(static_cast<uint32_t>\\([0-9]+\\)\\)" actions "${generated}")
string(REGEX REPLACE "set_effect\\(static_cast<uint32_t>\\(([0-9]+)\\)\\)" "\\1" actions "${actions}")
set(expected "1;2;3;4;5;6;7;8;9;10;0;1;0")
if(NOT "${actions}" STREQUAL "${expected}")
  message(FATAL_ERROR "Static effect indices differ: ${actions}")
endif()
if(generated MATCHES "new .*LightEffect|add_effects\\(\\{[^}]+\\}\\)")
  message(FATAL_ERROR "Metadata generated duplicate runtime effects")
endif()
file(READ "${PROJECT_DIR}/tests/fixtures/unknown-effect.yaml" effects)
string(REPLACE "esphome:\n" "" effects "${effects}")
string(REPLACE "  build_path: ${OUTPUT_DIR}/build\n" "  build_path: ${OUTPUT_DIR}/build\n${effects}" content "${base}")
check_case(unknown-effect "${content}" FALSE "Available effects:.*SOS.*Custom Rainbow")
string(REPLACE "Unlisted effect" "Slow Rainbow" legacy_content "${content}")
check_case(legacy-rainbow-effect "${legacy_content}" FALSE "Available effects:.*SOS.*Custom Rainbow")
string(REPLACE "  id: pixel_controller\n" "  id: pixel_controller\n  effects: [{lambda: {name: Arbitrary}}]\n" content "${base}")
check_case(arbitrary-effect "${content}" FALSE "effects.*invalid option|invalid option.*effects")
file(READ "${PROJECT_DIR}/tests/fixtures/multi-device.yaml" multiple)
string(FIND "${base}" "yiscaxia:\n" component_begin)
string(SUBSTRING "${base}" 0 ${component_begin} platform)
string(FIND "${multiple}" "yiscaxia:\n" multiple_begin)
string(SUBSTRING "${multiple}" 0 ${multiple_begin} devices)
string(REPLACE "esphome:\n" "" devices "${devices}")
string(REPLACE "  build_path: ${OUTPUT_DIR}/build\n" "  build_path: ${OUTPUT_DIR}/multi-build\n${devices}" platform "${platform}")
string(SUBSTRING "${multiple}" ${multiple_begin} -1 controllers)
set(content "${platform}${controllers}")
check_case(multi-device "${content}" TRUE "")
execute_process(COMMAND "${CMAKE_COMMAND}" -E env PYTHONDONTWRITEBYTECODE=1
    "${ESPHOME_EXECUTABLE}" compile "${OUTPUT_DIR}/multi-device.yaml" --only-generate
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 120)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "multi-device codegen failed: ${output}${error}")
endif()
file(READ "${OUTPUT_DIR}/multi-build/src/main.cpp" generated)
check_typed_positions("${OUTPUT_DIR}/multi-build/src/main.cpp" 24)
foreach(setting IN ITEMS pairs attempts spacing)
  if(NOT generated MATCHES "${setting}_a->set_device_\\(panel_a\\)" OR NOT generated MATCHES "${setting}_b->set_device_\\(panel_b\\)")
    message(FATAL_ERROR "Missing distinct device binding for ${setting}")
  endif()
endforeach()
string(REPLACE "device_id: panel_b" "device_id: panel_a" duplicate "${content}")
check_case(duplicate-setting-name "${duplicate}" FALSE "Duplicate|duplicate|already")
